<?php

return [
    'payment_types' => [
        'balance' => '1',
        'balance_point' => '2',
        'silk' => '3',
        'silk_gift' => '4',
        'silk_point' => '5',
        'item' => 6,

        // Vice versa for visual
        '1' => 'Bakiye',
        '2' => 'Bakiye (Puan)',
        '3' => 'Silk',
        '4' => 'Silk (Gift)',
        '5' => 'Silk (Point)',
        '6' => 'Item',
    ],
    'silk' => [
        'type' => [
            'name' => [
                '0' => 'silk_own',
                '1' => 'silk_gift',
                '2' => 'silk_point',
            ],
            'id' => [
                'silk_own' => '0',
                'silk_gift' => '1',
                'silk_point' => '2',
            ],
        ],
        'reason' => [
            'inc' => [
                'silk_own' => '0',
                'silk_gift' => '2',
                'silk_point' => '4',
            ],
            'dec' => [
                'silk_own' => '1',
                'silk_gift' => '3',
                'silk_point' => '5',
            ],
        ],
    ],
    'balance' => [
        'type' => [
            'balance' => 'balance',
            'point' => 'balance_point',
        ],
        'source' => [
            'admin' => '0',
            'deposit' => '1',
            'epin' => '2',
            'itemmall' => '3',
            'vote' => '4',
            'sent_to_user' => '5',
            'sent_by_user' => '6',
            'referred_user_reward' => '7',
            'itemmall_reward' => '8',
        ],
        'source_desc' => [
            '0' => 'Yönetici tarafından verildi',
            '1' => 'Bakiye yüklemesi',
            '2' => 'E-Pin',
            '3' => 'Item Mall',
            '4' => 'Vote Sistemi',
            '5' => 'Kullanıcıya gönderildi',
            '6' => 'Kullanıcı gönderdi',
            '7' => 'Referans olunan kullanıcının yaptığı alışverişten kazanıldı',
            '8' => 'Item Mall\'da yapılan alışverişten kazanıldı',
        ],
        'type_by_id' => [
            '1' => 'Bakiye',
            '2' => 'Bakiye (Puan)',
        ],
        'log_type' => [
            'balance' => '1',
            'balance_point' => '2',
        ],
    ],
    'itemmall' => [
        'limitations' => [
            'bitwise' => [
                'all' => -1,
                'balance' => 1,
                'balance_point' => 2,
                'silk' => 4,
                'silk_gift' => 8,
                'silk_point' => 16,
            ],
            'from_payment_type' => [
                '1' => 1,
                '2' => 2,
                '3' => 4,
                '4' => 8,
                '5' => 16,
            ],
        ],
    ],
    'inventory' => [
        'slots' => [
            'helm' => '0',
            'chest' => '1',
            'shoulders' => '2',
            'gauntlet' => '3',
            'pants' => '4',
            'boots' => '5',
            'weapon' => '6',
            'shield' => '7',
            'job' => '8',
            'earring' => '9',
            'necklace' => '10',
            'lring' => '11',
            'rring' => '12',
        ],
    ],
    'item' => [
        'rarity' => [
            '0' => 'Normal',
            '1' => 'Seal of Nova',
            '2' => 'Seal of Moon',
            '3' => 'Seal of Sun',
            '6' => 'Set',
        ],
        'country' => [
            '0' => 'Chinese',
            '1' => 'Europe',
        ],
        'white_stats' => [
            'param_names' => [
                'weapon' => ['Durability', 'PhyReinforce', 'MagReinforce', 'HitRatio', 'PhyAttack', 'MagAttack', 'CriticalRatio'], // 7
                'equipment' => ['Durability', 'PhyReinforce', 'MagReinforce', 'PhyDefense', 'MagDefense', 'ParryRatio'], // 6
                'shield' => ['Durability', 'PhyReinforce', 'MagReinforce', 'BlockRatio', 'PhyDefense', 'MagDefense'], // 6
                'accessory' => ['PhyAbsorption', 'MagAbsorption'], // 2
            ],
        ],
        'typeid' => [
            '1' => [
                'name' => 'Garment',
                '1' => 'Head',
                '2' => 'Shoulder',
                '3' => 'Body',
                '4' => 'Leg',
                '5' => 'Arm',
                '6' => 'Foot',
            ],
            '2' => [
                'name' => 'Protector',
                '1' => 'Head',
                '2' => 'Shoulder',
                '3' => 'Body',
                '4' => 'Leg',
                '5' => 'Arm',
                '6' => 'Foot',
            ],
            '3' => [
                'name' => 'Armor',
                '1' => 'Head',
                '2' => 'Shoulder',
                '3' => 'Body',
                '4' => 'Leg',
                '5' => 'Arm',
                '6' => 'Foot',
            ],
            '4' => [
                'name' => 'Shield',
                '1' => 'Chinese',
                '2' => 'European',
            ],
            '5' => [
                'name' => 'Accessory',
                '1' => 'Earring',
                '2' => 'Necklace',
                '3' => 'Ring',
            ],
            '6' => [
                'name' => 'Weapon',
                '1' => 'Unknown',
                '2' => 'Sword',
                '3' => 'Blade',
                '4' => 'Spear',
                '5' => 'Glavie',
                '6' => 'Bow',
                '7' => 'One-handed Sword',
                '8' => 'Two-handed Sword',
                '9' => 'Axe',
                '10' => 'Dark Staff',
                '11' => 'Staff',
                '12' => 'Crossbow',
                '13' => 'Dagger',
                '14' => 'Harp',
                '15' => 'Cleric Rod',
                '16' => 'Fortress Hammer',
            ],
            '7' => [
                'name' => 'Trade Item',
                '1' => 'Trader',
                '2' => 'Thief',
                '3' => 'Hunter',
            ],
            '9' => [
                'name' => 'Robe',
                '1' => 'Head',
                '2' => 'Shoulder',
                '3' => 'Body',
                '4' => 'Leg',
                '5' => 'Arm',
                '6' => 'Foot',
            ],
            '10' => [
                'name' => 'Light Armor',
                '1' => 'Head',
                '2' => 'Shoulder',
                '3' => 'Body',
                '4' => 'Leg',
                '5' => 'Arm',
                '6' => 'Foot',
            ],
            '11' => [
                'name' => 'Heavy Armor',
                '1' => 'Head',
                '2' => 'Shoulder',
                '3' => 'Body',
                '4' => 'Leg',
                '5' => 'Arm',
                '6' => 'Foot',
            ],
            '12' => [
                'name' => 'Accessory',
                '1' => 'Earring',
                '2' => 'Necklace',
                '3' => 'Ring',
            ],
            '13' => [
                'name' => 'Avatar',
                '1' => 'Hat',
                '2' => 'Body',
                '3' => 'Attachment',
                '4' => 'Flag',
            ],
            '14' => [
                'name' => 'Devil Spirit',
                '1' => 'Devil Spirit',
            ],
        ],
        'magic_attributes' => [
            'MATTR_APE' => 'Attribute Assimilation : %d Time/times',
            'MATTR_ASTRAL' => 'Astral(%dTime/times)',
            'MATTR_ATHANASIA' => 'Immortal(%dTime/times)',
            'MATTR_AVATAR_DARA' => 'Damage Absorption %d%%',
            'MATTR_AVATAR_DRUA' => 'Damage %d%% Increase',
            'MATTR_AVATAR_ER' => 'Parry rate %d%% Increase',
            'MATTR_AVATAR_HP' => 'HP %d Increase',
            'MATTR_AVATAR_HPRG' => 'HP Recovery %d%% Increase',
            'MATTR_AVATAR_HR' => 'Attack Rate %d%% Increase',
            'MATTR_AVATAR_INT' => 'Int %d Increase',
            'MATTR_AVATAR_INT_2' => 'Int %d Increase',
            'MATTR_AVATAR_INT_3' => 'Int %d Increase',
            'MATTR_AVATAR_INT_4' => 'Int %d Increase',
            'MATTR_AVATAR_LUCK' => 'Lucky %d%% Increase',
            'MATTR_AVATAR_LUCK_2' => 'Lucky %d%% Increase',
            'MATTR_AVATAR_LUCK_3' => 'Lucky %d%% Increase',
            'MATTR_AVATAR_LUCK_4' => 'Lucky %d%% Increase',
            'MATTR_AVATAR_MDIA' => 'Ignore Monster Defense %d%% Probability',
            'MATTR_AVATAR_MDIA_2' => 'Ignore Monster Defense %d%% Probability',
            'MATTR_AVATAR_MDIA_3' => 'Ignore Monster Defense %d%% Probability',
            'MATTR_AVATAR_MDIA_4' => 'Ignore Monster Defense %d%% Probability',
            'MATTR_AVATAR_MP' => 'MP %d Increase',
            'MATTR_AVATAR_MPRG' => 'MP Recovery %d%% Increase',
            'MATTR_AVATAR_STR' => 'Str %d Increase',
            'MATTR_AVATAR_STR_2' => 'Str %d Increase',
            'MATTR_AVATAR_STR_3' => 'Str %d Increase',
            'MATTR_AVATAR_STR_4' => 'Str %d Increase',
            'MATTR_BLOCKRATE' => 'Blocking rate %d Increase',
            'MATTR_CRITICAL' => 'Critical %d Increase',
            'MATTR_DEC_MAXDUR' => 'Maximum durability %d%% Reduce',
            'MATTR_DUR' => 'Durability %d%% Increase',
            'MATTR_DUR_SET' => 'Durability %d%% Increase',
            'MATTR_ER' => 'Parry rate %d%% Increase',
            'MATTR_ER_SET' => 'Parry rate %d%% Increase',
            'MATTR_EVADE_BLOCK' => 'Blocking rate %d',
            'MATTR_EVADE_CRITICAL' => 'Critical %d',
            'MATTR_HP' => 'HP %d Increase',
            'MATTR_HP_SET' => 'HP %d Increase',
            'MATTR_HR' => 'Attack Rate %d%% Increase',
            'MATTR_INT' => 'Int %d Increase',
            'MATTR_INT_3JOB' => 'Int %d Increase',
            'MATTR_INT_AVATAR' => 'Int %d Increase',
            'MATTR_INT_SET' => 'Int %d Increase',
            'MATTR_LUCK' => 'Lucky(%dTime/times)',
            'MATTR_LUCK_SET' => 'Lucky(%dTime/times)',
            'MATTR_MP' => 'MP %d Increase',
            'MATTR_MP_SET' => 'MP %d Increase',
            'MATTR_NASRUN_BLOCKRATE' => 'Blocking rate %d Increase',
            'MATTR_NASRUN_HPNA' => 'MaximumHP %d%% Increase',
            'MATTR_NASRUN_MPNA' => 'MaximumMP %d%% Increase',
            'MATTR_NASRUN_UMDU' => '%d%% Damage increase (it will apply to Unique monsters only)',
            'MATTR_NOT_REPARABLE' => 'Repair invalid (Maximum durability %d%% Increase)',
            'MATTR_REGENHPMP' => 'HP recovery/MP recovery %d%% Increase',
            'MATTR_REINFORCE_ITEM' => '+%d enhancement(0Second)',
            'MATTR_REINFORCE_ITEM_SET' => '',
            'MATTR_REPAIR' => 'Available Number of Repair(%dTime/times)',
            'MATTR_RESIST_ALL_SET' => '',
            'MATTR_RESIST_BURN' => 'BurnHour %d%% Reduce',
            'MATTR_RESIST_CSMP' => 'CombustionProbability %d%% Reduce',
            'MATTR_RESIST_DISEASE' => 'DiseaseProbability %d%% Reduce',
            'MATTR_RESIST_ESHOCK' => 'Electric shockHour %d%% Reduce',
            'MATTR_RESIST_FEAR' => 'FearProbability %d%% Reduce',
            'MATTR_RESIST_FROSTBITE' => 'Freezing,FrosbiteHour %d%% Reduce',
            'MATTR_RESIST_POISON' => 'PoisoningHour %d%% Reduce',
            'MATTR_RESIST_SLEEP' => 'SleepProbability %d%% Reduce',
            'MATTR_RESIST_STUN' => 'StunProbability %d%% Reduce',
            'MATTR_RESIST_ZOMBIE' => 'ZombieHour %d%% Reduce',
            'MATTR_SOLID' => 'Steady(%dTime/times)',
            'MATTR_STR' => 'Str %d Increase',
            'MATTR_STR_3JOB' => 'Str %d Increase',
            'MATTR_STR_AVATAR' => 'Str %d Increase',
            'MATTR_STR_SET' => 'Str %d Increase',
            'MATTR_TRADE_HP' => 'HP %d Increase',
            'MATTR_TRADE_HP_2' => 'HP %d Increase',
            'MATTR_TRADE_HP_3' => 'HP %d Increase',
            'MATTR_TRADE_INT' => 'Int %d Increase',
            'MATTR_TRADE_INT_2' => 'Int %d Increase',
            'MATTR_TRADE_INT_3' => 'Int %d Increase',
            'MATTR_TRADE_MP' => 'MP %d Increase',
            'MATTR_TRADE_MP_2' => 'MP %d Increase',
            'MATTR_TRADE_MP_3' => 'MP %d Increase',
            'MATTR_TRADE_STR' => 'Str %d Increase',
            'MATTR_TRADE_STR_2' => 'Str %d Increase',
            'MATTR_TRADE_STR_3' => 'Str %d Increase',
        ],
    ],
    'job' => [
        '0' => 'None',
        '1' => 'Trader',
        '2' => 'Thief',
        '3' => 'Hunter',

        'none' => '0',
        'trader' => '1',
        'thief' => '2',
        'hunter' => '3',
    ],
    'skill' => [
    ],
    'skillmastery' => [
        'names' => [
            // MasteryID => Name
            '257' => 'Blade',
            '258' => 'Glavie',
            '259' => 'Bow',
            '273' => 'Cold',
            '274' => 'Lightning',
            '275' => 'Fire',
            '276' => 'Force',

            '513' => 'Warrior',
            '514' => 'Wizard',
            '515' => 'Rogue',
            '516' => 'Warlock',
            '517' => 'Bard',
            '518' => 'Cleric',
        ],
    ],
    'guild' => [
        'permission' => [
            'all' => -1,
            'join' => 1,
            'withdraw' => 2,
            'union' => 4,
            'storage' => 8,
            'notice' => 16,
        ],
        'siege' => [
            '1' => 'Commander',
            '2' => 'Deputy Commander',
            '4' => 'Fortress War Administrator',
            '8' => 'Production Administrator',
            '16' => 'Training Administrator',
            '32' => 'Military Engineer',
        ],
    ],
    'siege' => [
        'names' => [
            // SiegeID => Name
            '1' => 'Jangan',
            '3' => 'Hotan',
            '4' => 'Constantinople',
            '6' => 'Bandit',
        ],
    ],
    'punishment' => [
        'login' => '1',
        'login_inspection' => '2',
        'p2p_trade' => '3',
        'chat' => '4',
    ],
    'punishment_type' => [
        '1' => [
            'text' => 'Login',
            'class' => 'badge-soft-primary',
        ],
        '2' => [
            'text' => 'Login (Inspection)',
            'class' => 'badge-soft-info',
        ],
        '3' => [
            'text' => 'P2P Trade',
            'class' => 'badge-soft-warning',
        ],
        '4' => [
            'text' => 'Chat',
            'class' => 'badge-soft-danger',
        ],
    ],
    'punishment_array' => [
        '1',
        '2',
        '3',
        '4',
    ],
    'ticket_system' => [
        'priority' => [
            '0' => [
                'name' => 'Low',
                'color' => 'btn-light',
                'adminclass' => 'btn-falcon-default',
            ],
            '1' => [
                'name' => 'Below Normal',
                'color' => 'btn-light',
                'adminclass' => 'btn-falcon-info',
            ],
            '2' => [
                'name' => 'Normal',
                'color' => 'btn-info',
                'adminclass' => 'btn-falcon-success',
            ],
            '3' => [
                'name' => 'Above Normal',
                'color' => 'btn-primary',
                'adminclass' => 'btn-falcon-primary',
            ],
            '4' => [
                'name' => 'High',
                'color' => 'btn-warning',
                'adminclass' => 'btn-falcon-warning',
            ],
            '5' => [
                'name' => 'Urgent!',
                'color' => 'btn-danger',
                'adminclass' => 'btn-falcon-danger',
            ],
        ],
        'priority_array' => [
            '0',
            '1',
            '2',
            '3',
            '4',
            '5',
        ],
        'status_array' => [
            '0',
            '1',
            '2',
            '3',
        ],
        'status' => [
            '0' => [
                'name' => 'New',
                'color' => 'btn-primary',
                'adminclass' => 'btn-falcon-primary',
            ],
            '1' => [
                'name' => 'Answered',
                'color' => 'btn-success',
                'adminclass' => 'btn-falcon-success',
            ],
            '2' => [
                'name' => 'Not Answered',
                'color' => 'btn-warning',
                'adminclass' => 'btn-falcon-warning',
            ],
            '3' => [
                'name' => 'Closed',
                'color' => 'btn-danger',
                'adminclass' => 'btn-falcon-danger',
            ],
        ],
        'status_from_name' => [
            'New' => '0',
            'Answered' => '1',
            'NotAnswered' => '2',
            'Closed' => '3',
        ],
    ],
];
